// Wishing well: what to toss in to get an item. From the FarmRPG wiki "WW Wants" page (2026-03-13, pasted by the player;
// buddy.farm's wishingWellOutputItems carries the same data). Hand-kept: add rows as the wiki grows.
// want[item] = [[toss in, chance % per toss], ...]
(function (root) {
  const WW = { want: {
    "4-leaf Clover": [["Old Boot", 33.3], ["Shark Tooth", 33.3]],
    "Amethyst": [["Aquamarine", 25], ["Jade", 25]],
    "Ancient Coin": [["Old Boot", 33.3], ["Taffy", 33.3]],
    "Antler": [["Pine Cone", 33.3]],
    "Apple": [["Candy", 25]],
    "Aquamarine": [["Jade", 25]],
    "Arrowhead": [["Antler", 33.3]],
    "Bacon": [["Dice", 25], ["Gold Cucumber", 33.3], ["Gold Eggplant", 25], ["Gold Feather", 33.3], ["Shark Tooth", 33.3]],
    "Bell": [["Grasshopper", 50]],
    "Bird Egg": [["Antler", 33.3]],
    "Blue Purse": [["Red Dye", 33.3], ["Steel Plate", 33.3]],
    "Borgen Bag 01": [["Fish Biscuit", 100], ["Hummingbird Feeder", 100]],
    "Broccoli": [["Salt", 50]],
    "Candy": [["Chattering Teeth", 25], ["Lollipop", 33.3], ["Taffy", 33.3]],
    "Candy Corn": [["Gouda", 33.3], ["Jack-o-lantern", 33.3], ["R.O.A.S.", 33.3], ["Treat Bag 03", 33.3]],
    "Canoe": [["Spoon", 33.3]],
    "Captains Log": [["Ancient Coin", 8.33], ["Pirate Bandana", 25], ["Small Flute", 20], ["Teapot", 14.3]],
    "Carved Bear": [["Block of Wood", 6.25], ["Pirate Bandana", 25]],
    "Carved Camel": [["Block of Wood", 6.25], ["Carved Owl", 33.3]],
    "Carved Chicken": [["Block of Wood", 6.25], ["Wooden Box", 25]],
    "Carved Cow": [["Block of Wood", 6.25], ["Carved Bear", 25]],
    "Carved Dragon": [["Block of Wood", 6.25]],
    "Carved Fox": [["Block of Wood", 6.25], ["Carved Bear", 25], ["Wooden Box", 25]],
    "Carved Kitty": [["Block of Wood", 6.25], ["Carved Rabbit", 25]],
    "Carved Moose": [["Block of Wood", 6.25], ["Carved Bear", 25], ["Carved Warthog", 25]],
    "Carved Mouse": [["Block of Wood", 6.25], ["Carved Rabbit", 25]],
    "Carved Owl": [["Block of Wood", 6.25], ["Carved Rabbit", 25], ["Teapot", 14.3], ["Wooden Mask", 33.3]],
    "Carved Pig": [["Block of Wood", 6.25]],
    "Carved Rabbit": [["Block of Wood", 6.25], ["Carved Warthog", 25]],
    "Carved Rhino": [["Block of Wood", 6.25], ["Carved Bear", 25], ["Carved Owl", 33.3], ["Teapot", 14.3]],
    "Carved Squirrel": [["Block of Wood", 6.25], ["Carved Warthog", 25], ["Spectacles", 20]],
    "Carved Squisquatch": [["Block of Wood", 6.25], ["Carved Warthog", 25]],
    "Carved Warthog": [["Block of Wood", 6.25], ["Carved Owl", 33.3], ["Carved Rabbit", 25], ["Small Flute", 20], ["Teapot", 14.3]],
    "Caterpillar": [["Fire Ant", 25], ["Shiny Beetle", 25], ["Snail", 25]],
    "Chattering Teeth": [["Gouda", 33.3], ["Witch Hat", 33.3]],
    "Chum": [["Essence of Slime", 50]],
    "Coal": [["Dragonfly", 33.3]],
    "Cogwheel": [["Ancient Coin", 8.33], ["Pocket Watch", 33.3]],
    "Corn": [["Herbs", 16.7]],
    "Crab Claw": [["Frog", 33.3], ["Orange Gecko", 33.3]],
    "Dancer": [["Milk and Cookies", 25]],
    "Dice": [["Small Flute", 20], ["Spectacles", 20], ["Strange Letter", 25], ["Wooden Pipe", 25]],
    "Egg 02": [["Dragonfly", 33.3]],
    "Egyptian Necklace": [["Candy Corn", 33.3], ["Treat Bag 02", 33.3]],
    "Emberstone": [["Jade", 25]],
    "Emerald": [["Aquamarine", 25]],
    "Energy Coil": [["Belt Drive", 33.3]],
    "Eye Patch": [["Ancient Coin", 8.33], ["Captains Log", 25], ["Pirate Bandana", 25]],
    "Fancy Box": [["Small Gear", 33.3]],
    "Fancy Drum": [["Sea Dragon", 33.3], ["Sturdy Bow", 33.3]],
    "Fancy Guitar": [["Sturdy Bow", 33.3]],
    "Fancy Pipe": [["Wooden Pipe", 25]],
    "Fire Ant": [["Caterpillar", 25], ["Horned Beetle", 25]],
    "Flamejack": [["Herbs", 16.7]],
    "Freaky Picture": [["Ancient Coin", 8.33], ["Strange Letter", 25], ["Teapot", 14.3]],
    "Frog": [["Crab Claw", 33.3], ["Orange Gecko", 33.3], ["Sea Dragon", 33.3]],
    "Giant Centipede": [["Ancient Coin", 8.33], ["Caterpillar", 25], ["Fire Ant", 25], ["Horned Beetle", 25]],
    "Glass Bottle": [["Old Boot", 33.3]],
    "Gold Carrot": [["Gold Cucumber", 33.3], ["Gold Eggplant", 25], ["Gold Peppers", 20]],
    "Gold Catfish": [["Gold Drum", 33.3], ["Goldfin", 33.3], ["Gold Flier", 33.3], ["Goldgill", 33.3]],
    "Gold Coral": [["Gold Sea Bass", 33.3]],
    "Gold Cucumber": [["Gold Carrot", 25], ["Gold Peas", 25], ["Gold Peppers", 20]],
    "Gold Drum": [["Goldray", 33.3]],
    "Gold Eggplant": [["Gold Carrot", 25], ["Gold Cucumber", 33.3], ["Gold Peas", 25], ["Gold Peppers", 20]],
    "Gold Feather": [["Bacon", 33.3], ["Gold Leaf", 33.3], ["Gold Peas", 25], ["Runestone 04", 33.3], ["Runestone 06", 25], ["Runestone 08", 33.3], ["Runestone 09", 33.3]],
    "Goldfin": [["Gold Coral", 50], ["Goldgill", 33.3], ["Gold Sea Bass", 33.3]],
    "Goldfish": [["Jack-o-lantern", 33.3]],
    "Gold Flier": [["Goldray", 33.3], ["Gold Sea Bass", 33.3], ["Gold Trout", 33.3]],
    "Goldgill": [["Gold Catfish", 33.3], ["Gold Flier", 33.3], ["Goldjack", 33.3], ["Gold Trout", 33.3]],
    "Goldjack": [["Gold Catfish", 33.3], ["Goldfin", 33.3], ["Goldgill", 33.3]],
    "Gold Leaf": [["Bacon", 33.3], ["Gold Eggplant", 25], ["Gold Feather", 33.3], ["Magicite", 25], ["Runestone 04", 33.3], ["Runestone 06", 25], ["Runestone 07", 33.3]],
    "Gold Peas": [["Gold Carrot", 25], ["Gold Eggplant", 25], ["Gold Peppers", 20]],
    "Gold Peppers": [["Gold Peas", 25]],
    "Goldray": [["Goldjack", 33.3], ["Gold Trout", 33.3]],
    "Gold Sea Bass": [["Gold Flier", 33.3], ["Goldjack", 33.3], ["Herbs", 16.7]],
    "Gold Trout": [["Gold Drum", 33.3], ["Goldfin", 33.3], ["Goldray", 33.3]],
    "Gouda": [["Small Gear", 33.3], ["Wax Candle", 33.3]],
    "Grab Bag 02": [["Water Lily", 33.3]],
    "Grab Bag 07": [["Milk and Cookies", 25]],
    "Green Jellyfish": [["Herbs", 16.7]],
    "Holiday Wreath": [["Milk and Cookies", 25]],
    "Honey": [["Herbs", 16.7]],
    "Horn": [["Pine Cone", 33.3]],
    "Horned Beetle": [["Fire Ant", 25], ["Giant Centipede", 25], ["Shiny Beetle", 25], ["Snail", 25]],
    "Iced Tea": [["Apple Cider", 33.3]],
    "Jack-o-lantern": [["Treat Bag 03", 33.3]],
    "Lemonade": [["Apple Cider", 33.3]],
    "Lemon Quartz": [["Aquamarine", 25]],
    "Lollipop": [["Candy", 25], ["Chattering Teeth", 25], ["Taffy", 33.3]],
    "Machine Press": [["Sturdy Bow", 33.3]],
    "Magicite": [["Bacon", 33.3], ["Gold Leaf", 33.3], ["Runestone 02", 25], ["Runestone 05", 25]],
    "Magna Core": [["Compass", 100]],
    "Magna Quartz": [["Runestone 02", 25], ["Runestone 05", 25]],
    "Metal Spool": [["Belt Drive", 33.3]],
    "MIAB": [["4-leaf Clover", 33.3]],
    "Monster Skull": [["Steel Plate", 33.3]],
    "Moonstone": [["Captains Log", 25], ["Eye Patch", 25], ["Runestone 01", 33.3], ["Runestone 03", 33.3], ["Shark Tooth", 33.3], ["Treat Bag 03", 33.3]],
    "Mug of Beer": [["Cutlass", 33.3]],
    "Mushroom Paste": [["Water Lily", 33.3]],
    "Octopus": [["Ancient Coin", 8.33], ["Herbs", 16.7]],
    "Onyx Scorpion": [["Spoon", 33.3]],
    "Orange Gecko": [["Ancient Coin", 8.33], ["Crab Claw", 33.3], ["Frog", 33.3], ["Sea Dragon", 33.3]],
    "Orange Juice": [["Apple Cider", 33.3]],
    "Pine Cone": [["Antler", 33.3]],
    "Pirate Bandana": [["Pocket Watch", 33.3], ["Spectacles", 20]],
    "Pirate Flag": [["Captains Log", 25], ["Freaky Picture", 25], ["Pirate Bandana", 25], ["Teapot", 14.3]],
    "Pocket Watch": [["Cogwheel", 25]],
    "Popcorn": [["Water Lily", 33.3]],
    "Prism Shard": [["Pine Cone", 33.3]],
    "Purple Bag": [["Red Dye", 33.3]],
    "Red Shield": [["Red Dye", 33.3]],
    "R.O.A.S.": [["Candy Corn", 33.3], ["Wax Candle", 33.3]],
    "Rubber Duckie": [["Cutlass", 33.3]],
    "Ruby": [["Aquamarine", 25], ["Jade", 25]],
    "Runestone 01": [["Eye Patch", 25], ["Gold Peppers", 20], ["Magicite", 25], ["Moonstone", 25], ["Runestone 02", 25]],
    "Runestone 02": [["Eye Patch", 25], ["Magicite", 25], ["Moonstone", 25], ["Runestone 01", 33.3], ["Teapot", 14.3]],
    "Runestone 03": [["Runestone 02", 25], ["Runestone 04", 33.3]],
    "Runestone 04": [["Runestone 03", 33.3], ["Runestone 05", 25]],
    "Runestone 05": [["Gold Feather", 33.3], ["Runestone 03", 33.3], ["Shiny Beetle", 25]],
    "Runestone 06": [["Horned Beetle", 25], ["Runestone 05", 25], ["Runestone 10", 33.3]],
    "Runestone 07": [["Giant Centipede", 25], ["Gold Leaf", 33.3], ["Moonstone", 25], ["Runestone 06", 25]],
    "Runestone 08": [["Fire Ant", 25], ["Runestone 07", 33.3], ["Runestone 09", 33.3], ["Runestone 10", 33.3]],
    "Runestone 09": [["Caterpillar", 25], ["Runestone 08", 33.3], ["Runestone 10", 33.3]],
    "Runestone 10": [["Runestone 06", 25], ["Runestone 07", 33.3], ["Runestone 08", 33.3], ["Runestone 09", 33.3], ["Snail", 25]],
    "Sea Dragon": [["Crab Claw", 33.3], ["Frog", 33.3], ["Orange Gecko", 33.3]],
    "Sealed Letter": [["Pirate Flag", 25]],
    "Shark Tooth": [["Cutlass", 33.3]],
    "Shiny Beetle": [["Ancient Coin", 8.33], ["Caterpillar", 25], ["Giant Centipede", 25], ["Horned Beetle", 25], ["Snail", 25]],
    "Small Flute": [["4-leaf Clover", 33.3], ["Cogwheel", 25], ["Dice", 25], ["Pirate Flag", 25], ["Wooden Mask", 33.3], ["Wooden Pipe", 25]],
    "Small Gear": [["Ancient Coin", 8.33], ["Freaky Picture", 25], ["Pirate Flag", 25], ["Wooden Pipe", 25]],
    "Small Key": [["Large Chest 01", 33.3], ["Large Chest 02", 33.3]],
    "Small Screw": [["Ancient Coin", 8.33], ["Cogwheel", 25], ["Small Flute", 20], ["Small Spring", 25], ["Spectacles", 20], ["Strange Letter", 25]],
    "Small Spring": [["Freaky Picture", 25]],
    "Snail": [["Ancient Coin", 8.33], ["Giant Centipede", 25], ["Shiny Beetle", 25]],
    "Spectacles": [["Dice", 25], ["Eye Patch", 25], ["Pirate Flag", 25], ["Small Spring", 25], ["Strange Letter", 25], ["Wooden Mask", 33.3]],
    "Spider": [["Candy", 25], ["Grasshopper", 50], ["Jack-o-lantern", 33.3], ["Lollipop", 33.3]],
    "Spiked Shell": [["Salt", 50]],
    "Spool of Copper": [["Belt Drive", 33.3]],
    "Square Key": [["Large Chest 01", 33.3], ["Large Chest 02", 33.3], ["R.O.A.S.", 33.3], ["Treat Bag 02", 33.3]],
    "Stone": [["Dragonfly", 33.3]],
    "Strange Letter": [["Captains Log", 25], ["Gold Carrot", 25], ["Magicite", 25], ["Moonstone", 25], ["Runestone 01", 33.3], ["Small Flute", 20], ["Small Spring", 25]],
    "Sturdy Bow": [["Gold Coral", 50], ["Gold Drum", 33.3]],
    "Taffy": [["Candy", 25], ["Candy Corn", 33.3], ["Lollipop", 33.3], ["R.O.A.S.", 33.3], ["Treat Bag 02", 33.3]],
    "Teapot": [["Dice", 25], ["Freaky Picture", 25]],
    "Treasure Chest": [["Wooden Box", 25]],
    "Treasure Key": [["Large Chest 01", 33.3], ["Large Chest 02", 33.3]],
    "Treat Bag 01": [["Chattering Teeth", 25]],
    "Vixen": [["Milk and Cookies", 25]],
    "Wax Candle": [["Ancient Coin", 8.33], ["Gouda", 33.3], ["Small Gear", 33.3], ["Witch Hat", 33.3]],
    "Witch Hat": [["Chattering Teeth", 25], ["Wax Candle", 33.3]],
    "Wizard Hat": [["Witch Hat", 33.3]],
    "Wooden Bow": [["Essence of Slime", 50], ["Gold Catfish", 33.3]],
    "Wooden Mask": [["4-leaf Clover", 33.3], ["Cogwheel", 25], ["Pocket Watch", 33.3], ["Wooden Box", 25]],
    "Wooden Pipe": [["Small Spring", 25], ["Spectacles", 20]],
    "Wrench": [["Spoon", 33.3], ["Steel Plate", 33.3]]
  } };
  if (typeof module !== "undefined" && module.exports) module.exports = WW;
  else root.WW = WW;
})(typeof window !== "undefined" ? window : globalThis);
