// Snapshot seeds from buddy.farm into seeds.js: growth time and what each seed grows.
// Run: node tools/snapshot-seeds.js   (one request per seed)
// crops[crop] = [{ seed, minutes, perCrop }]  where perCrop = seeds planted per crop harvested (0.1 = 10 crops per seed)
const fs = require("fs"), path = require("path");
const BASE = "https://buddy.farm/page-data/i";
const slug = name => name.toLowerCase().replace(/[.]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const SEEDS = ["Beet", "Broccoli", "Cabbage", "Carrot", "Corn", "Cotton", "Cucumber", "Eggplant", "Gold Carrot", "Gold Cucumber",
  "Gold Eggplant", "Gold Pea", "Gold Pepper", "Hops", "Leek", "Onion", "Pea", "Pepper", "Pine", "Potato", "Pumpkin", "Radish",
  "Rice", "Sugar Cane", "Sunflower", "Tomato", "Watermelon", "Wheat"].map(n => n + " Seeds")
  .concat(["Mushroom Spores", "Mega Beet Seeds", "Mega Cotton Seeds", "Mega Pine Seeds", "Mega Sunflower Seeds"]);
const TREE = { Pine: "Pine Tree" };                                         // seed name -> crop name when they differ
const NO_DATA = { "Gold Pea Seeds": "Gold Peas", "Gold Pepper Seeds": "Gold Peppers" };  // seeds buddy.farm has no drop list for
const TEN_X = ["Mushroom Spores"];                                          // item text says "Grows 10x Mushrooms"

(async () => {
  const crops = {}, missing = [];
  for (const seed of SEEDS) {
    const r = await fetch(`${BASE}/${slug(seed)}/page-data.json`);
    const it = r.ok && (await r.json()).result.data.farmrpg.items[0];
    if (!it) { missing.push(seed); continue; }
    let crop = null, perCrop = null;
    const items = (it.dropRates[0] && it.dropRates[0].items) || [];
    if (items.length) {                                                    // main crop = the most common drop
      const best = items.reduce((a, b) => (a.rate < b.rate ? a : b));
      crop = best.item.name; perCrop = +best.rate.toPrecision(4);
    } else if (seed.startsWith("Mega ")) {                                 // mega seeds grow 10x the normal crop
      const base = seed.replace(/^Mega /, "").replace(/ Seeds$/, "");
      crop = TREE[base] || base; perCrop = 0.1;
    }
    if (!crop && !seed.startsWith("Mega ")) { crop = NO_DATA[seed] || seed.replace(/ Seeds$/, ""); perCrop = 1; }   // one crop per seed
    if (TEN_X.includes(seed)) perCrop = 0.1;
    if (!crop) { missing.push(seed + " (no crop found)"); continue; }
    (crops[crop] ||= []).push({ seed, minutes: it.baseYieldMinutes, perCrop });
    await new Promise(r => setTimeout(r, 100));
  }
  const out = `// Generated by tools/snapshot-seeds.js from buddy.farm on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.
// crops[crop] = [{ seed, minutes (base growth time), perCrop (seeds per crop; 0.1 = 10 crops per seed) }]
(function (root) {
  const SEEDS = ${JSON.stringify({ crops })};
  if (typeof module !== "undefined" && module.exports) module.exports = SEEDS;
  else root.SEEDS = SEEDS;
})(typeof window !== "undefined" ? window : globalThis);
`;
  fs.writeFileSync(path.join(__dirname, "..", "seeds.js"), out);
  console.log(`${Object.keys(crops).length} crops from ${SEEDS.length - missing.length} seeds`);
  if (missing.length) console.log("missing:", missing.join(", "));
})();
