// Snapshot crafting/cooking recipes from buddy.farm into recipes.js.
// Run: node tools/snapshot-recipes.js   (several hundred small requests, 4 at a time with a short pause)
// Starts from every item in drops.js, tower.js and the test fixtures, then follows recipes both ways:
// ingredients (what an item is made from) and uses (what it's made into, for outlets).
const fs = require("fs"), path = require("path");
const root = path.join(__dirname, "..");
const BASE = "https://buddy.farm/page-data/i";
const slug = name => name.toLowerCase().replace(/[.]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const sleep = ms => new Promise(r => setTimeout(r, ms));

async function get(name) {
  for (let tries = 0; tries < 3; tries++) {
    const r = await fetch(`${BASE}/${slug(name)}/page-data.json`);
    if (r.ok) return r.json();
    if (r.status === 404) return null;
    await sleep(1000 * (tries + 1));
  }
  return null;
}

(async () => {
  const DROPS = require(path.join(root, "drops.js"));
  const TOWER = require(path.join(root, "tower.js"));
  const { parseMastery } = require(path.join(root, "parse.js"));
  const seeds = new Set(Object.keys(DROPS.items));
  for (const req of Object.values(TOWER.levels)) for (const n of [...(req.gm || []), ...(req.mm || [])]) seeds.add(n);
  const fx = path.join(root, "test", "fixtures", "mastery-trimmed.txt");
  if (fs.existsSync(fx)) for (const n of Object.keys(parseMastery(fs.readFileSync(fx, "utf8")).items)) seeds.add(n);
  const extra = path.join(__dirname, "seeds.txt");                      // optional: one item name per line
  if (fs.existsSync(extra)) for (const n of fs.readFileSync(extra, "utf8").split(/\r?\n/)) if (n.trim()) seeds.add(n.trim());

  const queue = [...seeds], seen = new Set(queue), items = {}, missing = [];
  let active = 0, done = 0;
  const add = n => { if (!seen.has(n)) { seen.add(n); queue.push(n); } };
  await new Promise(resolve => {
    const pump = () => {
      if (!queue.length && !active) return resolve();
      while (active < 4 && queue.length) {
        const name = queue.shift();
        active++;
        get(name).then(j => {
          const it = j && j.result.data.farmrpg.items[0];
          if (!it) missing.push(name);
          else {
            const recipe = it.recipeItems.map(r => [r.item.name, r.quantity]);
            const uses = it.recipeIngredientItems.map(r => [r.item.name, r.quantity]);
            items[it.name] = {
              id: it.id, craft: it.canCraft, cook: it.canCook, level: it.canCraft ? it.craftingLevel : it.cookingLevel,
              mail: it.canMail, ...(recipe.length ? { recipe } : {}), ...(uses.length ? { uses } : {})
            };
            recipe.forEach(([n]) => add(n));
            uses.forEach(([n]) => add(n));
          }
        }).catch(e => missing.push(`${name} (${e.message})`)).finally(async () => {
          active--; done++;
          if (done % 100 === 0) console.log(`${done} fetched, ${queue.length} queued`);
          await sleep(100);
          pump();
        });
      }
    };
    pump();
  });

  const out = `// Generated by tools/snapshot-recipes.js from buddy.farm on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.
// items[name] = { id, craft, cook, level, mail, recipe?: [[ingredient, qty]], uses?: [[product, qtyOfThisPerCraft]] }
(function (root) {
  const RECIPES = ${JSON.stringify({ items })};
  if (typeof module !== "undefined" && module.exports) module.exports = RECIPES;
  else root.RECIPES = RECIPES;
})(typeof window !== "undefined" ? window : globalThis);
`;
  fs.writeFileSync(path.join(root, "recipes.js"), out);
  const withRecipe = Object.values(items).filter(i => i.recipe).length;
  console.log(`${Object.keys(items).length} items (${withRecipe} with recipes), ${(out.length / 1024).toFixed(0)} KB`);
  if (missing.length) console.log(`not found (${missing.length}): ${missing.slice(0, 30).join(", ")}${missing.length > 30 ? "…" : ""}`);
})();
