// Snapshot townsfolk gift preferences from buddy.farm into npcs.js.
// Run: node tools/snapshot-npcs.js   (one request per townsperson)
// npcs[name] = { loves: [items], likes: [items], hates: [items], special: { item: xp } (super-loved items with their own XP) }
const fs = require("fs"), path = require("path");
const BASE = "https://buddy.farm/page-data";
const slug = name => name.toLowerCase().replace(/[.']/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

(async () => {
  const list = (await (await fetch(`${BASE}/townsfolk/page-data.json`)).json()).result.data.farmrpg.npcs.map(n => n.name);
  const npcs = {}, missing = [];
  for (const name of list) {
    const r = await fetch(`${BASE}/t/${slug(name)}/page-data.json`);
    const n = r.ok && (await r.json()).result.data.farmrpg.npcs[0];
    if (!n) { missing.push(name); continue; }
    const o = { loves: [], likes: [], hates: [] };
    for (const x of n.npcItems || []) {
      const key = x.relationship === "loves" ? "loves" : x.relationship === "likes" ? "likes" : x.relationship === "hates" ? "hates" : null;
      if (key) o[key].push(x.item.name);
      if (x.specialXp) (o.special ||= {})[x.item.name] = x.specialXp;
    }
    npcs[name] = o;
    await new Promise(r => setTimeout(r, 100));
  }
  const out = `// Generated by tools/snapshot-npcs.js from buddy.farm on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.
// npcs[name] = { loves: [items], likes: [items], hates: [items], special: { item: xp } }
(function (root) {
  const NPCS = ${JSON.stringify({ npcs })};
  if (typeof module !== "undefined" && module.exports) module.exports = NPCS;
  else root.NPCS = NPCS;
})(typeof window !== "undefined" ? window : globalThis);
`;
  fs.writeFileSync(path.join(__dirname, "..", "npcs.js"), out);
  console.log(`${Object.keys(npcs).length} of ${list.length} townsfolk`);
  if (missing.length) console.log("missing:", missing.join(", "));
})();
