// Snapshot explore + fishing drop rates from buddy.farm into drops.js.
// Run: node tools/snapshot-drops.js   (about 30 small requests, 4 at a time)
// Rates are "explores per drop" (explore) or "fishes per drop" (fishing), exactly as buddy.farm stores them.
const fs = require("fs"), path = require("path");
const BASE = "https://buddy.farm/page-data";
const slug = name => name.toLowerCase().replace(/[.]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const get = async url => { const r = await fetch(url); if (!r.ok) throw new Error(`${r.status} ${url}`); return r.json(); };

async function pool(list, n, fn) {
  const out = []; let i = 0;
  await Promise.all(Array.from({ length: n }, async () => { while (i < list.length) { const k = i++; out[k] = await fn(list[k]); } }));
  return out;
}

(async () => {
  const idx = [];
  for (const kind of ["exploring", "fishing"]) {
    const j = await get(`${BASE}/${kind}/page-data.json`);
    for (const l of j.result.data.farmrpg.locations) idx.push(l.name);
  }
  const locs = {}, items = {};
  const pages = await pool(idx, 4, async name => {
    try { return await get(`${BASE}/l/${slug(name)}/page-data.json`); }
    catch (e) { console.warn("skip", name, e.message); return null; }
  });
  for (const pg of pages) {
    const l = pg && pg.result.data.farmrpg.locations[0];
    if (!l) continue;
    locs[l.name] = { type: l.type, base: l.baseDropRate, xp: {}, silver: {} };
    for (const v of l.dropRates) {
      // Variant key: explore drops depend on the Iron Depot and Runecube perks; fishing on net vs manual and Runecube.
      // Fishing variants with manualFishing === null are the seasonal frozen pond (winter only), so they're skipped.
      if (l.type === "fishing" && v.manualFishing == null) continue;
      const key = l.type === "fishing" ? `${v.manualFishing ? "manual" : "net"}${v.runecube ? "R" : ""}`
        : `${v.ironDepot ? "D" : ""}${v.runecube ? "R" : ""}` || "-";
      // Average XP and sell value per explore (or per fish), by variant; keep the better one if a variant is listed twice
      if (v.xpPerHit != null) locs[l.name].xp[key] = Math.max(locs[l.name].xp[key] ?? 0, +v.xpPerHit.toPrecision(5));
      if (v.silverPerHit != null) locs[l.name].silver[key] = Math.max(locs[l.name].silver[key] ?? 0, +v.silverPerHit.toPrecision(5));
      for (const d of v.items) {
        const it = items[d.item.name] ||= { id: d.item.id, manualOnly: !!d.item.manualFishingOnly, drops: {} };
        const at = it.drops[l.name] ||= {};
        // Some locations list the same variant twice (a later-unlock pool); keep the better rate
        at[key] = Math.min(at[key] ?? Infinity, +d.rate.toPrecision(5));
      }
    }
  }
  const out = `// Generated by tools/snapshot-drops.js from buddy.farm on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.
// locs[name] = {type: "explore"|"fishing", base: baseDropRate, xp: {variant: XP per explore/fish}, silver: {variant: silver per explore/fish}}; items[name].drops[loc][variant] = explores (or fishes) per drop.
// Explore variants: "-" none, "D" Iron Depot, "R" Runecube, "DR" both. Fishing variants: "net", "netR", "manual", "manualR" (R = Runecube); frozen-pond (winter) rates left out.
(function (root) {
  const DROPS = ${JSON.stringify({ locs, items })};
  if (typeof module !== "undefined" && module.exports) module.exports = DROPS;
  else root.DROPS = DROPS;
})(typeof window !== "undefined" ? window : globalThis);
`;
  fs.writeFileSync(path.join(__dirname, "..", "drops.js"), out);
  console.log(`${Object.keys(locs).length} locations, ${Object.keys(items).length} items, ${(out.length / 1024).toFixed(0)} KB`);
})();
