// Snapshot quests from buddy.farm into quests.js.
// Run: node tools/snapshot-quests.js   (one request per quest, 4 at a time with a short pause; ~10 minutes)
// Skips quests that have already ended (past endDate). Keeps requirements, rewards and the chain links both ways.
const fs = require("fs"), path = require("path");
const root = path.join(__dirname, "..");
const BASE = "https://buddy.farm/page-data";
// Quest slugs keep a trailing "-" for trailing punctuation ("Lost at Sea?" -> lost-at-sea-) and drop <br/> line breaks
const slug = name => name.replace(/<br\s*\/?>/gi, " ").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-/, "");
const clean = name => name.replace(/<br\s*\/?>/gi, " ").replace(/\s+/g, " ").trim();   // names as the game page shows them
const sleep = ms => new Promise(r => setTimeout(r, ms));

async function get(url) {
  for (let tries = 0; tries < 3; tries++) {
    const r = await fetch(url);
    if (r.ok) return r.json();
    if (r.status === 404) return null;
    await sleep(1000 * (tries + 1));
  }
  return null;
}

(async () => {
  const list = (await get(`${BASE}/quests/page-data.json`)).result.data.farmrpg.quests;
  const now = Date.now();
  const todo = list.filter(q => !q.endDate || Date.parse(q.endDate) >= now);
  console.log(`${list.length} quests, ${todo.length} not ended`);
  const quests = {}, missing = [];
  let i = 0, done = 0;
  await Promise.all(Array.from({ length: 4 }, async () => {
    while (i < todo.length) {
      const q = todo[i++];
      const j = await get(`${BASE}/q/${slug(q.name)}/page-data.json`).catch(() => null);
      const d = j && j.result.data.farmrpg.quests[0];
      if (!d) missing.push(q.name);
      else {
        const lv = {};
        for (const k of ["Farming", "Fishing", "Crafting", "Exploring", "Cooking", "Tower"]) if (d[`required${k}Level`]) lv[k] = d[`required${k}Level`];
        quests[clean(d.name)] = {
          id: q.id, npc: d.npc, line: (q.questlines[0] && q.questlines[0].questline.title) || null,
          ...(d.startDate ? { start: d.startDate.slice(0, 10) } : {}), ...(d.endDate ? { end: d.endDate.slice(0, 10) } : {}),
          ...(d.isHidden ? { hidden: true } : {}),
          need: d.requiredItems.map(r => [r.item.name, r.quantity]),
          ...(Object.keys(lv).length ? { lv } : {}),
          ...(d.requiredSilver ? { silver: d.requiredSilver } : {}),
          ...(d.requiredNpc ? { friend: [d.requiredNpc, d.requiredNpcLevel] } : {}),
          get: d.rewardItems.map(r => [r.item.name, r.quantity]),
          ...(d.rewardSilver ? { rSilver: d.rewardSilver } : {}), ...(d.rewardGold ? { rGold: d.rewardGold } : {}),
          ...(d.pred ? { pred: clean(d.pred.name) } : {}),
          ...(d.dependentQuests.length ? { next: d.dependentQuests.map(x => clean(x.name)) } : {})
        };
      }
      if (++done % 250 === 0) console.log(`${done} fetched`);
      await sleep(100);
    }
  }));
  const out = `// Generated by tools/snapshot-quests.js from buddy.farm on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.
// quests[name] = { id, npc, line, start?, end?, need: [[item, qty]], lv?: {Skill: level}, silver?, friend?: [npc, level],
//                  get: [[item, qty]], rSilver?, rGold?, pred?: name, next?: [names] }
(function (root) {
  const QUESTS = ${JSON.stringify({ quests })};
  if (typeof module !== "undefined" && module.exports) module.exports = QUESTS;
  else root.QUESTS = QUESTS;
})(typeof window !== "undefined" ? window : globalThis);
`;
  fs.writeFileSync(path.join(root, "quests.js"), out);
  console.log(`${Object.keys(quests).length} quests, ${(out.length / 1024).toFixed(0)} KB`);
  if (missing.length) console.log(`not found (${missing.length}): ${missing.slice(0, 20).join(", ")}${missing.length > 20 ? "…" : ""}`);
})();
