// Snapshot trade-chat prices from farmrpg-trade.live into trade.js.
// Run: node tools/snapshot-trade.js   (one request)
// trade[item] = { ap: median AP per item, gold: median gold per item, n: priced trades in the last 7 days }.
// When an item has no AP trades, its AP price comes from its gold price at the going AP-for-gold rate
// (the median gold price of an Arnold Palmer).
const fs = require("fs"), path = require("path");

(async () => {
  // limit 1000 is the most the API allows; that covers every item it tracks
  const r = await fetch("https://farmrpg-trade.live/api/trpc/items.list?input=" + encodeURIComponent(JSON.stringify({ json: { limit: 1000, sort: "liquidity" } })) + "");
  const list = (await r.json()).result.data.json;
  const ap = list.find(i => i.name === "Arnold Palmer");
  const goldPerAp = ap && ap.medianGold;                                   // gold for one AP
  const trade = {};
  for (const i of list) {
    if (!i.pricedTrades) continue;
    const apPer = i.nAp >= 3 ? i.medianAp : i.medianGold != null && goldPerAp ? i.medianGold / goldPerAp : null;
    if (apPer == null) continue;
    trade[i.name] = { ap: +apPer.toPrecision(4), ...(i.medianGold != null ? { gold: +i.medianGold.toPrecision(4) } : {}), n: i.pricedTrades };
  }
  const out = `// Generated by tools/snapshot-trade.js from farmrpg-trade.live on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.
// trade[item] = { ap: median AP per item (from gold at ${goldPerAp} gold per AP when AP trades are scarce), gold?, n: priced trades (7 days) }
(function (root) {
  const TRADE = ${JSON.stringify({ goldPerAp, trade })};
  if (typeof module !== "undefined" && module.exports) module.exports = TRADE;
  else root.TRADE = TRADE;
})(typeof window !== "undefined" ? window : globalThis);
`;
  fs.writeFileSync(path.join(__dirname, "..", "trade.js"), out);
  console.log(`${list.length} items listed, ${Object.keys(trade).length} priced, ${(out.length / 1024).toFixed(0)} KB, 1 AP = ${goldPerAp} gold`);
})();
