// Snapshot meals from buddy.farm into meals.js: cooking level, cook time and effect for every cookable item in recipes.js.
// Run: node tools/snapshot-meals.js   (one request per meal)
// meals[name] = { level (cooking level), minutes (base cook time), effect (the game's description) }
const fs = require("fs"), path = require("path");
const RECIPES = require("../recipes.js");
const BASE = "https://buddy.farm/page-data/i";
const slug = name => name.toLowerCase().replace(/[.]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

(async () => {
  const meals = {}, missing = [];
  const names = Object.keys(RECIPES.items).filter(n => RECIPES.items[n].cook);
  for (const name of names) {
    const r = await fetch(`${BASE}/${slug(name)}/page-data.json`);
    const it = r.ok && (await r.json()).result.data.farmrpg.items[0];
    if (!it) { missing.push(name); continue; }
    meals[name] = { level: it.cookingLevel, minutes: it.baseYieldMinutes, effect: it.description || "" };
    await new Promise(r => setTimeout(r, 100));
  }
  const out = `// Generated by tools/snapshot-meals.js from buddy.farm on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.
// meals[name] = { level (cooking level), minutes (base cook time), effect (the game's description) }
(function (root) {
  const MEALS = ${JSON.stringify({ meals })};
  if (typeof module !== "undefined" && module.exports) module.exports = MEALS;
  else root.MEALS = MEALS;
})(typeof window !== "undefined" ? window : globalThis);
`;
  fs.writeFileSync(path.join(__dirname, "..", "meals.js"), out);
  console.log(`${Object.keys(meals).length} of ${names.length} meals`);
  if (missing.length) console.log("missing:", missing.join(", "));
})();
