// Snapshot what chests, bags and boxes contain (Locksmith) into loot.js, for every quest reward item.
// Run: node tools/snapshot-loot.js   (one request per reward item not already known to have a recipe or drops)
// loot[item] = { grab: true if you get ONE random entry (grab bags), key?: key item used up, gold?: gold inside,
//                out: [[item, min, max]] }
const fs = require("fs"), path = require("path");
const root = path.join(__dirname, "..");
const BASE = "https://buddy.farm/page-data/i";
const slug = name => name.toLowerCase().replace(/[.]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const sleep = ms => new Promise(r => setTimeout(r, ms));

(async () => {
  const Q = require(path.join(root, "quests.js")).quests;
  const names = new Set();
  for (const q of Object.values(Q)) for (const [n] of q.get) names.add(n);
  const loot = {};
  let i = 0;
  const list = [...names];
  await Promise.all(Array.from({ length: 4 }, async () => {
    while (i < list.length) {
      const name = list[i++];
      const r = await fetch(`${BASE}/${slug(name)}/page-data.json`).catch(() => null);
      const it = r && r.ok && (await r.json()).result.data.farmrpg.items[0];
      if (it && it.locksmithItems.length) {
        loot[it.name] = {
          ...(it.locksmithGrabBag ? { grab: true } : {}),
          ...(it.locksmithKey ? { key: it.locksmithKey.name } : {}),
          ...(it.locksmithGold ? { gold: it.locksmithGold } : {}),
          out: it.locksmithItems.map(o => [o.outputItem.name, o.quantityMin, o.quantityMax])
        };
      }
      await sleep(100);
    }
  }));
  const out = `// Generated by tools/snapshot-loot.js from buddy.farm on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.
// loot[item] = { grab?: one random entry, key?: key used up, gold?, out: [[item, min, max]] }
(function (root) {
  const LOOT = ${JSON.stringify({ loot })};
  if (typeof module !== "undefined" && module.exports) module.exports = LOOT;
  else root.LOOT = LOOT;
})(typeof window !== "undefined" ? window : globalThis);
`;
  fs.writeFileSync(path.join(root, "loot.js"), out);
  console.log(`${list.length} reward items checked, ${Object.keys(loot).length} containers, ${(out.length / 1024).toFixed(0)} KB`);
})();
