// Snapshot every buddy.farm item's ID into items.js (used by savecode.js so QR codes carry IDs, not names).
// Run: node tools/snapshot-items.js         adds items not in items.js yet (few requests)
//      node tools/snapshot-items.js --all   recrawls everything (~1,300+ requests, 4 at a time with a short pause)
// Extra names to start from (items no other page links to, e.g. old event collectibles): tools/item-seeds.txt, one per line.
// buddy.farm has no "all items" page, so this starts from every item name the planner's data already knows, plus every item
// on buddy.farm's list pages (Exchange Center, level rewards, passwords, cards, Tower, each location and each townsperson),
// and follows the items each item page mentions (drops, recipes, quests, ...), until no new names turn up.
const fs = require("fs"), path = require("path");
const root = path.join(__dirname, "..");
const BASE = "https://buddy.farm/page-data/i";
const slug = name => name.toLowerCase().replace(/[.]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const sleep = ms => new Promise(r => setTimeout(r, ms));

async function get(name, page) {
  for (let tries = 0; tries < 3; tries++) {
    try {
      const r = await fetch(page ? `https://buddy.farm/page-data/${page}/page-data.json` : `${BASE}/${slug(name)}/page-data.json`);
      if (r.ok) return r.json();
      if (r.status === 404) return null;
    } catch (e) {}
    await sleep(1000 * (tries + 1));
  }
  return null;
}
// Every { __typename: "FarmRPG_Item", name, id? } anywhere in a page
function walk(o, found) {
  if (Array.isArray(o)) { for (const x of o) walk(x, found); return; }
  if (!o || typeof o !== "object") return;
  if (o.__typename === "FarmRPG_Item" && typeof o.name === "string") found.push([o.name, o.id]);
  for (const v of Object.values(o)) walk(v, found);
}

(async () => {
  const req = f => { try { return require(path.join(root, f)); } catch (e) { return null; } };
  const names = new Set();
  const R = req("recipes.js");
  for (const [n, x] of Object.entries(R.items)) { names.add(n); for (const [i] of [...(x.recipe || []), ...(x.uses || [])]) names.add(i); }
  const Q = req("quests.js");
  for (const q of Object.values(Q.quests)) for (const [i] of [...(q.need || []), ...(q.get || [])]) names.add(i);
  const D = req("drops.js");
  if (D && D.items) for (const n of Object.keys(D.items)) names.add(n);
  const N = req("npcs.js");
  if (N) for (const x of Object.values(N.npcs || N)) for (const k of ["loves", "likes", "hates"]) for (const i of x[k] || []) names.add(Array.isArray(i) ? i[0] : i);

  for (const f of ["seeds.txt", "item-seeds.txt"]) {
    const file = path.join(__dirname, f);
    if (fs.existsSync(file)) for (const n of fs.readFileSync(file, "utf8").split(/\r?\n/)) if (n.trim()) names.add(n.trim());
  }
  // buddy.farm list pages, and one page per location (/l/...) and townsperson (/t/...)
  const pages = ["exchange-center", "level-rewards", "passwords", "cards", "tower"];
  for (const idx of ["exploring", "fishing"]) {
    const p = await get(null, idx);
    for (const l of (p && p.result.data.farmrpg.locations) || []) pages.push("l/" + slug(l.name));
  }
  const tf = await get(null, "townsfolk");
  for (const n of (tf && tf.result.data.farmrpg.npcs) || []) pages.push("t/" + slug(n.name));
  const fromPages = [];
  for (let i = 0; i < pages.length; i += 4) {
    for (const p of await Promise.all(pages.slice(i, i + 4).map(pg => get(null, pg)))) if (p) walk(p.result && p.result.data, fromPages);
    await sleep(150);
  }
  for (const [n] of fromPages) names.add(n);
  console.log(`${pages.length} list pages: ${new Set(fromPages.map(([n]) => n)).size} item names`);

  const ids = {}, done = new Set();
  for (const [n, x] of Object.entries(R.items)) if (x.id != null) ids[n] = x.id;
  if (!process.argv.includes("--all")) {
    const old = req("items.js") || {};
    for (const [n, id] of Object.entries(old)) { ids[n] = id; done.add(n); }
  }
  for (const [n, id] of fromPages) if (id != null && ids[n] == null) ids[n] = +id;
  const queue = [...names].filter(n => !done.has(n));
  while (queue.length) {
    const batch = queue.splice(0, 4).filter(n => !done.has(n));
    batch.forEach(n => done.add(n));
    const pages = await Promise.all(batch.map(get));
    pages.forEach((p, k) => {
      if (!p) return;
      const found = [];
      walk(p.result && p.result.data, found);
      for (const [n, id] of found) {
        if (id != null && ids[n] == null) ids[n] = +id;
        if (!done.has(n) && !queue.includes(n)) queue.push(n);
      }
      if (ids[batch[k]] == null) process.stdout.write(`\n(no ID on ${batch[k]})`);
    });
    process.stdout.write(`\r${done.size} pages, ${Object.keys(ids).length} IDs, ${queue.length} to go   `);
    await sleep(150);
  }
  const sorted = Object.fromEntries(Object.entries(ids).sort((a, b) => a[1] - b[1]));
  fs.writeFileSync(path.join(root, "items.js"),
    `// Generated by tools/snapshot-items.js from buddy.farm on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.\n` +
    `// ITEMS[name] = buddy.farm item ID (the game's own ID). savecode.js writes items by ID so QR codes stay short.\n` +
    `(function (root) {\n  const ITEMS = ${JSON.stringify(sorted)};\n` +
    `  if (typeof module !== "undefined" && module.exports) module.exports = ITEMS;\n  else root.ITEMS = ITEMS;\n` +
    `})(typeof window !== "undefined" ? window : globalThis);\n`);
  console.log(`\nwrote items.js: ${Object.keys(sorted).length} items`);
})();
